@echo off
echo Starting main.py...
start E:\dev\Projekte\manus\youtube\online\youtube_downloader_ui\venv\Scripts\python.exe main.py
echo Waiting for server to start...
timeout /t 5 /nobreak >nul
echo Checking server availability...
E:\dev\Projekte\manus\youtube\online\youtube_downloader_ui\venv\Scripts\python.exe wait_for_server.py
exit